spring.application.name=to-done

spring.datasource.url=jdbc:postgresql://localhost:5202/to-done
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true